name: Branch Protection Setup

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup branch protection
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          
          try {
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                checks: [
                  { context: 'test (3.9)' },
                  { context: 'test (3.10)' },
                  { context: 'test (3.11)' },
                  { context: 'test (3.12)' },
                  { context: 'format' }
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true
            });
            
            console.log('✅ Branch protection rules updated successfully');
          } catch (error) {
            console.log('ℹ️ Branch protection update failed (may require admin permissions):', error.message);
            console.log('💡 Please manually configure branch protection rules in GitHub repository settings');
            console.log('Required status checks: test (3.9), test (3.10), test (3.11), test (3.12), format');
          }